### ISSUE TITLE
How it works if I don't know the 'end' property value?

### ISSUE THREAD

**Issue by dearshor** [nvenky/excel-parser#1]
I've understood it works well if I definitely know the `start` and `end` properties of `@ExcelObject`, but what about if I don't ? For instance, I only know the `start`, I've no idea about the `end`. Can I loop a set of rows/columns ? And how to set the break condition?

**Comment by vershinin** [comment]
Any news on this?

**Comment by vershinin** [comment]
Hi!
Also, it would be nice, if you can publish updated version in maven repo :)
Thank you.
